name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    if: github.repository_owner == 'snowcrystals' && github.repository != 'snowcrystals/template'
    outputs:
      NAME: ${{ steps.env.outputs.NAME }}
      TYPE: ${{ steps.env.outputs.TYPE }}
      SHA: ${{ steps.env.outputs.SHA }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Use Node.js v16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Documentation
        run: yarn docs

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: docs
          path: docs/api.json

      - name: Set Output
        id: env
        run: |
          echo "NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "TYPE=${GITHUB_REF_TYPE}" >> $GITHUB_OUTPUT
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT

  upload:
    name: Upload Documentation
    needs: build
    runs-on: ubuntu-latest
    env:
      NAME: ${{ needs.build.outputs.NAME }}
      TYPE: ${{ needs.build.outputs.TYPE }}
      SHA: ${{ needs.build.outputs.SHA }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Use Node.js v16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.yarnpkg.org/

      - name: Install Dependencies
        run: yarn --immutable

      - name: Download Documentation Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: docs
          path: docs

      - name: Checkout Documentation Project
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          repository: "snowcrystals/docs"
          token: ${{ secrets.USER_TOKEN }}
          path: "out"

      - name: Move Documentation
        if: ${{ env.TYPE == 'tag' }}
        env:
          SEMVER: ${{ env.NAME }}
        run: |
          mkdir -p out/docs/${{ env.REPOSITORY }}
          mv docs/api.json out/docs/${{ env.REPOSITORY }}/${SEMVER}.json

      - name: Move Documentation
        if: ${{ env.TYPE == 'branch' }}
        run: |
          mkdir -p out/docs/${{ env.REPOSITORY }}
          mv docs/api.json out/docs/${{ env.REPOSITORY }}/${NAME}.json

      - name: Commit & Push
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 1
          command: |
            cd out
            git add .
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit, exiting with code 0"
              exit 0;
            else
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git config rebase.autostash true
              git config pull.rebase true
              git commit -m "docs(${{ env.REPOSITORY }}): build for ${TYPE} ${NAME}: ${SHA}" || true
              git pull
              git push
            fi
