name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    if: github.repository_owner == 'snowcrystals' && github.repository != 'snowcrystals/template'
    outputs:
      NAME: ${{ steps.env.outputs.NAME }}
      TYPE: ${{ steps.env.outputs.TYPE }}
      SHA: ${{ steps.env.outputs.SHA }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Documentation
        run: pnpm run docs

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/api.json

      - name: Set Output
        id: env
        run: |
          echo "NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "TYPE=${GITHUB_REF_TYPE}" >> $GITHUB_OUTPUT
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT

  upload:
    name: Upload Documentation
    needs: build
    runs-on: ubuntu-latest
    env:
      NAME: ${{ needs.build.outputs.NAME }}
      TYPE: ${{ needs.build.outputs.TYPE }}
      SHA: ${{ needs.build.outputs.SHA }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Download Documentation Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs

      - name: Checkout Documentation Project
        uses: actions/checkout@v4
        with:
          repository: "snowcrystals/docs"
          token: ${{ secrets.USER_TOKEN }}
          path: "out"

      - name: Move Documentation
        if: ${{ env.TYPE == 'tag' }}
        env:
          SEMVER: ${{ env.NAME }}
        run: |
          mkdir -p out/docs/${{ env.REPOSITORY }}
          mv docs/api.json out/docs/${{ env.REPOSITORY }}/${SEMVER}.json

      - name: Move Documentation
        if: ${{ env.TYPE == 'branch' }}
        run: |
          mkdir -p out/docs/${{ env.REPOSITORY }}
          mv docs/api.json out/docs/${{ env.REPOSITORY }}/${NAME}.json

      - name: Commit & Push
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 1
          command: |
            cd out
            git add .
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit, exiting with code 0"
              exit 0;
            else
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git config rebase.autostash true
              git config pull.rebase true
              git commit -m "docs(${{ env.REPOSITORY }}): build for ${TYPE} ${NAME}: ${SHA}" || true
              git pull
              git push
            fi
